nome = input ("Qual é o seu nome? ")
print ("Olá,",nome,", muito prazer!")
dia = input ("Qual é o dia do seu nascimento? ")
mes = input ("Qual é o mês do seu nascimento? ")
ano = input ("Qual é o ano do seu nascimento? ")
print ("Você nasceu no dia",dia, "de",mes, "de",ano,",correto?")
num1 = input ("Informe o primeiro número: ")
num2 = input ("Informe o segundo número: ")
soma = num1 + num2
print ("A soma entre os dois número é:",soma)